### PR TITLE
Abi 1.18

### PR DESCRIPTION
**Pull request by j34ni**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by minrk** [comment]
There is no abi 1.18. The latest (unreleased) ABI version is 1.8 in libfabric 2.0. Let's pause these builds until we have a plain. I don't believe we need to build every version of libfabric there ever was. I don't think we need to be maintaining builds for more than one libfabric version per ABI version at most, but we need run_exports to match.

**Comment by j34ni** [comment]
I am trying to find one version that builds without error between 1.20 and 1.15.2

**Comment by j34ni** [comment]
Mixed up version and ABI name

**Comment by minrk** [comment]
> I am trying to find one version that builds without error between 1.20 and 1.15.2

1.19 should work all the way back to 1.14 if the ABI claims are correct. Can you verify if that's true?

**Comment by minrk** [comment]
(I'm writing up a summary of the ABI builds tasks right now, which should help keep track of these things)

**Comment by j34ni** [comment]
ABI 1.5 ABI version starting with libfabric 1.13.
**ABI 1.6 ABI version starting with libfabric 1.14.** 
ABI 1.7 ABI version starting with libfabric 1.20.

**Pull request closed without merging**
