### PR TITLE
Add version 1.17.0

### PR DESCRIPTION
**Pull request by j34ni**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Adding version 1.17.0

### CODE REVIEW

**Comment by minrk** [comment]
We should be building these outdated versions in branches, not main. I think we can also reference the [abi changes](https://ofiwg.github.io/libfabric/main/man/fabric.7.html#abi-changes) to build one libfabric release per abi minor version (or just one 'oldest' version).

**Comment by minrk** [comment]
I think we can also make the outdated version builds linux-only, since mac builds aren't working and there's little reason to need outdated libfabric there.

**Comment by j34ni** [comment]
Closing this pull request to remake it from a fork of this feedstock

**Comment by minrk** [comment]
I made an `abi-16` branch for our builds targeting abi 1.6. It should have a run_exports lower bound of libfabric 1.14.0.

**Comment by j34ni** [comment]
I deleted the other `libfabric_1.17.0` branch then, and will use the one you created but why did you call it `abi-16` and which version of libfabric should we have there (1.16.0)?

**Pull request closed without merging**
